name: ZMusicBox
version: 1.0
api: [1.0.0]
author: ondraczsk
description: Music~~
main: ZMusicBox\ZMusicBox

commands:
 music:
  permission: ZMusicBox.music
  description: ZMusicBox's main command
  usage: /hudba <Dalsi|Start|Stop>

permissions:
 ZMusicBox:
  default: true
  description: ZMusicBox Commands
  children:
     ZMusicBox.music:
      default: true
      description: ZMusicBox Commands
    
