name: ZMusicBox
version: 2.6.0
api: [1.0.0]
author: Zzm
description: Music~~
main: ZMusicBox\ZMusicBox

commands:
 music:
  permission: ZMusicBox.music
  description: ZMusicBox's main command
  usage: /music <Next>

permissions:
 ZMusicBox:
  default: op
  description: ZMusicBox Commands
  children:
     ZMusicBox.music:
      default: op
      description: ZMusicBox Commands
    
